import re
from pathlib import Path


class FullStackQualityEngine:
    """Enforce product completeness on projects generated by Autarch."""

    REQUIRED_ROUTES = {
        "/": "apps/web/app/page.tsx",
        "/games": "apps/web/app/games/page.tsx",
        "/login": "apps/web/app/login/page.tsx",
        "/signup": "apps/web/app/signup/page.tsx",
        "/forgot-password": "apps/web/app/forgot-password/page.tsx",
        "/reset-password": "apps/web/app/reset-password/page.tsx",
        "/profile": "apps/web/app/profile/page.tsx",
        "/leaderboard": "apps/web/app/leaderboard/page.tsx",
        "/pricing": "apps/web/app/pricing/page.tsx",
        "/admin": "apps/web/app/admin/page.tsx",
        "/help": "apps/web/app/help/page.tsx",
        "/contact": "apps/web/app/contact/page.tsx",
        "/about": "apps/web/app/about/page.tsx",
        "/privacy": "apps/web/app/privacy/page.tsx",
        "/terms": "apps/web/app/terms/page.tsx",
    }

    def enhance(self, root: Path, brand: str, request: str = ""):
        self._write(root, "apps/web/components/AuthNav.tsx", self._auth_nav(brand))
        self._write(root, "apps/web/app/layout.tsx", self._layout(brand))
        self._write(root, "apps/web/app/forgot-password/page.tsx", self._forgot())
        self._write(root, "apps/web/app/reset-password/page.tsx", self._reset())
        self._write(root, "apps/web/app/help/page.tsx", self._info("Help Center", "Find answers, account guidance and troubleshooting steps.", [("Getting started", "Create an account, choose a game and open its preview."), ("Account support", "Use password recovery if you cannot sign in."), ("Technical support", "Contact the support team with the error and browser details.")]))
        self._write(root, "apps/web/app/contact/page.tsx", self._contact())
        self._write(root, "apps/web/app/about/page.tsx", self._info("About", f"{brand} is a connected competitive gaming platform generated by Autarch AI.", [("Our product", "One player identity across games, leaderboards and multiplayer rooms."), ("Our direction", "Build transparent, secure and entertaining online experiences.")]))
        self._write(root, "apps/web/app/privacy/page.tsx", self._info("Privacy", "A clear overview of how account and gameplay data is handled.", [("Account data", "Authentication and player profiles are stored in Supabase."), ("Payments", "Payment credentials are handled by the payment provider, not stored in the browser."), ("Your control", "Users should be able to review and delete their account data.")]))
        self._write(root, "apps/web/app/terms/page.tsx", self._info("Terms", "Rules for responsible use of the gaming platform.", [("Accounts", "Users are responsible for protecting their credentials."), ("Fair play", "Cheating, harassment and unauthorized access are prohibited."), ("Subscriptions", "Prices, renewal and cancellation terms must be shown before purchase.")]))
        self._write(root, "apps/web/lib/gameCatalog.ts", self._game_catalog())
        self._write(root, "apps/web/app/games/[slug]/page.tsx", self._game_preview())
        self._write(root, "apps/web/app/games/page.tsx", self._games_page())
        self._write(root, "apps/web/app/page.tsx", self._landing(brand))
        self._append_css(root)

    def audit(self, root: Path, request: str = ""):
        errors = []
        warnings = []
        for route, relative in self.REQUIRED_ROUTES.items():
            if not (root / relative).exists():
                errors.append(f"missing route {route}: {relative}")

        layout = self._read(root / "apps/web/app/layout.tsx")
        for required in ("AuthNav", "/help", "/contact", "/privacy", "/terms"):
            if required not in layout:
                errors.append(f"layout missing {required}")

        combined = "\n".join(
            self._read(path) for path in (root / "apps/web/app").rglob("*.tsx")
        )
        for href in re.findall(r'href=[{]?(["\'])(/[^"\']+)\1', combined):
            route = href[1].split("?")[0]
            if "${" in route or route.startswith("/games/"):
                continue
            if route not in self.REQUIRED_ROUTES:
                warnings.append(f"link target not covered by route audit: {route}")

        css = self._read(root / "apps/web/app/globals.css")
        if "@keyframes" not in css:
            errors.append("design missing animations")
        if ":hover" not in css or "scale(" not in css:
            errors.append("design missing interactive zoom treatment")
        if "image:" not in combined.lower() and "<img" not in combined and "backgroundimage" not in combined:
            errors.append("game experience missing imagery")
        requested_count = self._requested_game_count(request)
        catalog = self._read(root / "apps/web/lib/gameCatalog.ts")
        actual_count = catalog.count("slug:")
        if requested_count and actual_count < requested_count:
            errors.append(f"requested at least {requested_count} games, generated {actual_count}")
        if not (root / "apps/web/app/games/[slug]/page.tsx").exists():
            errors.append("missing playable game preview route")
        if 'href={`/games/${' not in combined:
            errors.append("game cards do not link to previews")
        if "create table" not in self._read(root / "supabase/schema.sql").lower():
            errors.append("database schema missing")
        return {"errors": errors, "warnings": sorted(set(warnings))}

    def _requested_game_count(self, request: str):
        match = re.search(r"(?:at least|minimum(?: of)?)\s+(\d+)\s+games?", request, re.I)
        return int(match.group(1)) if match else 0

    def _game_catalog(self):
        return '''export const games = [
  {slug:"neon-strike",title:"Neon Strike",genre:"Tactical arena",description:"Fast 5v5 rounds in a luminous cyber city.",image:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80"},
  {slug:"void-racers",title:"Void Racers",genre:"Space racing",description:"Race anti-gravity craft across collapsing star lanes.",image:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80"},
  {slug:"kingdom-siege",title:"Kingdom Siege",genre:"Strategy",description:"Build alliances and command massive fantasy battles.",image:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80"},
  {slug:"apex-drift",title:"Apex Drift",genre:"Arcade racing",description:"Master precision drifts on cinematic street circuits.",image:"https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80"},
  {slug:"shadow-protocol",title:"Shadow Protocol",genre:"Stealth",description:"Infiltrate guarded networks and escape unseen.",image:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80"},
  {slug:"titanfall-arena",title:"Titanfall Arena",genre:"Mech combat",description:"Pilot heavy mechs in destructible multiplayer arenas.",image:"https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=1200&q=80"},
  {slug:"mystic-realms",title:"Mystic Realms",genre:"Adventure",description:"Explore enchanted worlds with your online party.",image:"https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80"},
  {slug:"strike-zone",title:"Strike Zone",genre:"Battle royale",description:"Outthink rival squads in a shrinking combat zone.",image:"https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=1200&q=80"},
  {slug:"pixel-legends",title:"Pixel Legends",genre:"Retro RPG",description:"Collect heroes and conquer a handcrafted pixel world.",image:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80"}
];'''

    def _landing(self, brand: str):
        template = '''import Link from "next/link";import {games} from "../lib/gameCatalog";
export default function Home(){return <main><section className="hero"><span className="pill">LIVE COMPETITIVE GAMING</span><h1>PLAY. COMPETE.<br/><em>BECOME LEGEND.</em></h1><p>__BRAND__ brings games, live rooms, player profiles and global competition into one premium arena.</p><div className="actions"><Link className="primary" href="/signup">Create player</Link><Link className="secondary" href="/games">Explore games</Link></div></section><section><div className="sectionHead"><h2>Featured games</h2><Link href="/games">View all →</Link></div><div className="grid">{games.slice(0,6).map(g=><article className="game" key={g.slug}><Link className="imageLink" aria-label={`Open ${g.title} preview`} href={`/games/${g.slug}`}><div className="cover gameImage" style={{backgroundImage:`linear-gradient(180deg,transparent,#090a12),url(${g.image})`}}/></Link><small>{g.genre}</small><h3>{g.title}</h3><p>{g.description}</p><Link className="playLink" href={`/games/${g.slug}`}>Open preview →</Link></article>)}</div></section></main>}'''
        return template.replace("__BRAND__", brand)

    def _games_page(self):
        return '''import Link from "next/link";import {games} from "../../lib/gameCatalog";
export default function Games(){return <main><span className="pill">GAME LIBRARY</span><h1>Choose your next world</h1><div className="grid">{games.map(g=><article className="game" key={g.slug}><Link className="imageLink" aria-label={`Open ${g.title} preview`} href={`/games/${g.slug}`}><div className="cover gameImage" style={{backgroundImage:`linear-gradient(180deg,transparent,#090a12),url(${g.image})`}}/></Link><small>{g.genre}</small><h3>{g.title}</h3><p>{g.description}</p><Link className="playLink" href={`/games/${g.slug}`}>Open preview →</Link></article>)}</div></main>}'''

    def _game_preview(self):
        return '''import Link from "next/link";import {notFound} from "next/navigation";import {games} from "../../../lib/gameCatalog";
export default async function GamePreview({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const game=games.find(g=>g.slug===slug);if(!game)notFound();return <main><section className="previewHero" style={{backgroundImage:`linear-gradient(90deg,#090a12 10%,transparent),url(${game.image})`}}><span className="pill">{game.genre}</span><h1>{game.title}</h1><p>{game.description}</p><div className="actions"><button className="primary">Launch demo</button><Link className="secondary" href="/games">All games</Link></div></section><section className="panel"><h2>Game preview</h2><p>This interactive preview is ready to connect to the generated multiplayer API and player session.</p></section></main>}'''

    def _write(self, root: Path, relative: str, content: str):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.strip() + "\n", encoding="utf-8")

    def _read(self, path: Path):
        return path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""

    def _auth_nav(self, brand: str):
        return f'''"use client";
import Link from "next/link";
import {{ useEffect, useState }} from "react";
import {{ useRouter }} from "next/navigation";
import {{ supabase }} from "../lib/supabase";
export default function AuthNav() {{
  const [email,setEmail]=useState(""); const router=useRouter();
  useEffect(()=>{{supabase.auth.getSession().then(({{data}})=>setEmail(data.session?.user.email||""));const {{data}}=supabase.auth.onAuthStateChange((_e,s)=>setEmail(s?.user.email||""));return()=>data.subscription.unsubscribe()}},[]);
  async function logout(){{await supabase.auth.signOut();setEmail("");router.push("/");router.refresh()}}
  return <nav><Link className="brand" href="/">{brand}</Link><div><Link href="/games">Games</Link><Link href="/leaderboard">Leaderboard</Link><Link href="/pricing">Pricing</Link><Link href="/help">Help</Link>{{email?<><Link href="/profile">Profile</Link><button className="navLogout" onClick={{logout}}>Log out</button></>:<><Link href="/login">Log in</Link><Link className="navJoin" href="/signup">Join free</Link></>}}</div></nav>
}}'''

    def _layout(self, brand: str):
        return f'''import "./globals.css";
import Link from "next/link";
import AuthNav from "../components/AuthNav";
export const metadata={{title:"{brand}",description:"Competitive gaming, tournaments and community"}};
export default function Layout({{children}}:{{children:React.ReactNode}}){{return <html lang="en"><body><AuthNav/>{{children}}<footer><div><strong>{brand}</strong><p>One player identity across competitive worlds.</p></div><div><b>Product</b><Link href="/games">Games</Link><Link href="/leaderboard">Leaderboard</Link><Link href="/pricing">Pricing</Link></div><div><b>Support</b><Link href="/help">Help Center</Link><Link href="/contact">Contact</Link><Link href="/forgot-password">Reset password</Link></div><div><b>Company</b><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><small>© 2026 {brand} · Generated by Autarch AI</small></footer></body></html>}}'''

    def _forgot(self):
        return '''"use client";import {FormEvent,useState} from "react";import Link from "next/link";import {supabase} from "../../lib/supabase";
export default function Forgot(){const[email,setEmail]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setMsg(error?.message||"Check your email for the reset link.")}return <main><form className="auth" onSubmit={submit}><h1>Reset password</h1><p>Enter your account email.</p><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><button>Send reset link</button><p>{msg}</p><Link href="/login">Back to login</Link></form></main>}'''

    def _reset(self):
        return '''"use client";import {FormEvent,useState} from "react";import {supabase} from "../../lib/supabase";
export default function Reset(){const[password,setPassword]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.auth.updateUser({password});setMsg(error?.message||"Password updated. You can now log in.")}return <main><form className="auth" onSubmit={submit}><h1>Choose new password</h1><input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password"/><button>Update password</button><p>{msg}</p></form></main>}'''

    def _info(self, title: str, intro: str, sections):
        blocks = "".join(f'<section><h2>{heading}</h2><p>{text}</p></section>' for heading, text in sections)
        return f'''export default function Page(){{return <main className="infoPage"><span className="pill">PLAYER RESOURCE</span><h1>{title}</h1><p className="intro">{intro}</p>{blocks}</main>}}'''

    def _contact(self):
        return '''export default function Contact(){return <main className="infoPage"><span className="pill">SUPPORT</span><h1>Contact</h1><p className="intro">Need help with your account, billing or a game?</p><a className="contactCard" href="mailto:support@example.com?subject=Gaming%20Support"><small>EMAIL SUPPORT</small><strong>support@example.com</strong><span>Open your mail app →</span></a><section><h2>Before sending</h2><p>Include the page, device and exact error. Never send passwords or secret keys.</p></section></main>}'''

    def _append_css(self, root: Path):
        path = root / "apps/web/app/globals.css"
        css = self._read(path)
        extra = '''\nnav button.navLogout{margin-left:18px}.navJoin{padding:9px 13px;border-radius:9px;background:#7157ff;color:white!important}footer{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:30px;text-align:left}footer div{display:flex;flex-direction:column;gap:9px}footer a{color:#8992aa;text-decoration:none}footer small{grid-column:1/-1;border-top:1px solid #24263b;padding-top:20px}.infoPage{max-width:850px;margin:auto}.infoPage>h1{font-size:clamp(3rem,7vw,6rem)}.infoPage .intro{font-size:1.2rem;color:#aab0c4;line-height:1.7}.infoPage section{padding:25px 0;margin:0;border-top:1px solid #292d46}.contactCard{display:flex;flex-direction:column;gap:8px;margin:35px 0;padding:25px;border:1px solid #785dff;border-radius:18px;color:white;text-decoration:none;transition:.3s}.contactCard:hover{transform:translateY(-5px) scale(1.02);box-shadow:0 25px 60px #0008}@keyframes autarchPageIn{from{opacity:0;transform:scale(.94) translateY(12px)}to{opacity:1;transform:scale(1) translateY(0)}}main{animation:autarchPageIn .55s ease both}.game,.panel{transition:transform .3s ease,box-shadow .3s ease}.game:hover,.panel:hover{transform:translateY(-7px) scale(1.025);box-shadow:0 24px 60px #0008}.gameImage{min-height:210px;background-size:cover;background-position:center}.playLink{display:inline-flex;margin-top:12px;color:#fff;text-decoration:none;font-weight:800}.previewHero{min-height:64vh;border-radius:28px;padding:clamp(35px,8vw,100px);background-size:cover;background-position:center;display:flex;flex-direction:column;justify-content:flex-end}.previewHero h1{font-size:clamp(3.5rem,9vw,8rem);margin:.15em 0}.previewHero p{max-width:620px;font-size:1.2rem}@media(max-width:750px){footer{grid-template-columns:1fr 1fr}footer>div:first-child,footer small{grid-column:1/-1}}\n'''
        extra = extra.replace(
            ".gameImage{min-height:210px;background-size:cover;background-position:center}",
            ".imageLink{display:block;border-radius:12px;overflow:hidden}.gameImage{min-height:210px;background-size:cover;background-position:center;transition:transform .35s ease}.imageLink:hover .gameImage{transform:scale(1.06)}",
        )
        if "autarchPageIn" not in css:
            path.write_text(css.rstrip() + extra, encoding="utf-8")
